# Generated by Django 2.2.17 on 2021-01-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_data', '0001_UserData'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
